services:
  prometheus:
    image: ngurra-prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - staging-net
      - prod-net
      - monitoring-net
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  alertmanager:
    image: ngurra-alertmanager:latest
    ports:
      - "9093:9093"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3005:3000"
    networks:
      - monitoring-net
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  staging-net:
    external: true
  prod-net:
    external: true
  monitoring-net:
    external: true
  
volumes:
  grafana_data: